---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  KUBE_CONFIG:
  RELEASE_NAME:

inputs:
- name: ci

outputs:
- name: docker-mounts-privileged
- name: docker-mounts

run:
  path: ci/tasks/scripts/start-docker
  args: [ci/tasks/scripts/docker-mounts]
